### ISSUE TITLE
Can we add a database deployment or migration to the code base?

### ISSUE THREAD

**Issue by joshi1983** [Sananthu-47/Social_Feeds#2]
When deploying this web app to a new hosting or development environment, it would be nice to have a quick way to create the database schema.  An SQL script would be very simple and get the job done for now.

I started a script below by reverse engineering some of the queries from the PHP scripts but it is probably not complete or exactly what you want:
[init_db.sql.txt](https://github.com/Sananthu-47/Social_Feeds/files/5641200/init_db.sql.txt)

**Comment by Sananthu-47** [comment]
Yes thank you for the suggestion I have added the database file to the repo and I have edited the init_db_sql.txt file and attached here
[init_db.sql.txt](https://github.com/Sananthu-47/Social_Feeds/files/5641432/init_db.sql.txt)
Is this what we need for schema?

**Comment by joshi1983** [comment]
Yeah, that's good.  I overlooked the likes table and it is good that you made the varchar lengths match yours because 100 was a blind guess from me.

includes/db/init_db.sql might be a good place for it.

**Comment by Sananthu-47** [comment]
Ya will add this file in to the code. Should i automate this file while creating new tables or should edit ever time we add new tables?

**Comment by joshi1983** [comment]
This is your project so that's very much up to you.

If this was mine, I'd keep editing the same file as long as possible.  If the site is publicly running somewhere, it'll become important to separate changes to other scripts because you'll want to run only the new changes.  Until you really need to migrate, it can be simpler to drop all tables and recreate them using that script.

**Comment by Sananthu-47** [comment]
Okay thank you for the help 😊.
